name = "RestrictedBoltzmannMachinesHDF5"
uuid = "d76020e8-6658-45fa-bb6d-0aaddbb4b5e5"
authors = ["Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"]
version = "2.1.0-DEV"

[deps]
CenteredRBMs = "def70c09-f69f-4396-afd1-e8507a6dddbf"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"
StandardizedRestrictedBoltzmannMachines = "c8d9fdc7-1808-4fba-8c97-f848504396a5"

[compat]
CenteredRBMs = "4"
HDF5 = "0.16"
RestrictedBoltzmannMachines = "3"
StandardizedRestrictedBoltzmannMachines = "4"
julia = "1.9"
